[package]
name = "struct-diff-iter"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.32"
smallvec = "1.13.2"
itertools = "0.13.0"
struct-diff-iter-derive = { path = "struct-diff-iter-derive" }
struct-diff-iter-internal = { path = "struct-diff-iter-internal"}  